### ISSUE TITLE
UK Contracts Finder has control chars in JSON feed

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#103]
I tried to run the UK Contracts Finder scraper, but several hundred pages in there's an object that contains control characters. I've emailed them to ask that they fix their feed, but in the meantime, we should filter them out.

**Comment by timgdavies** [comment]
Ideal experience would, I think, be that, if we hit an error:

- We mark clearly in the database a failed file download with date if failed, and URL that failed
- We continue loading everything else

and/or

- If we can recover from the error, we still write something to the database to flag a 'warning' of some sort for the file and date.

**Comment by robredpath** [comment]
Thanks @timgdavies . My proposed behaviour, to be clear, is to just remove the control characters and then load the meaningful data. 

But, it sounds like it's important that we note times when we've had to apply any sort of fixes (we've done it in a few scrapers, and if it's simple things like removing control chars we don't log it at all). So, we should do that!

**Comment by timgdavies** [comment]
Definitely important to log any fixes we make. The user story for this would be:

> As an analyst reviewing a publishers data I want to be able to tell them about any issues that might make their data difficult to work with so that they can fix their data at source and future users can work with the data without encoding issues or other problems.

**Comment by odscjames** [comment]
If anyone wants to look at this it's easy to reproduce quickly, just go to UKContractsFinderSource -> gather_all_download_urls -> and change the for loop to

> for page in range(931, 935):

**Comment by odscjames** [comment]
The data values have weird characters in them - I'll break out a binary editor in a bit and try and have a look.

>       "description": "Award Notice - \r\nThe Authority's and it's partner Capita have awarded the Phase 2 construction works for the Central Lower Promenade \r\n reconstruction project.\r\n\r\n\r\n\r\n",

**Comment by odscjames** [comment]
The stack trace can be got rid of by changing https://github.com/open-contracting/ocdsdata/blob/master/ocdsdata/base.py#L201 , run_store function, to 

>        json_data = json.load(f, strict=False)

But I just want to have a play and try and work out if that has any other consequences of that.

BTW The control codes are:

> 19 04 02  07 02 05 11 0E 15 19 05 1A  07 14 17 04  12 0B 13 

Also I'm going to break the general discussion around the use case to another ticket, and this one can be on the specific error.

**Comment by odscjames** [comment]
Note that the fix for this (adding strict=false) isn't ideal because then we silently lose the fact there were problem characters here. See #105.

Noting that on #96 we are thinking about a framework wide thing to filter out certain characters WHILE logging that we are doing so. Maybe we want to use that same mechanism to also filter out these control characters, so that they can be logged in the same way.

**Comment by odscjames** [comment]
Closing this. The framework now filters out control chars, while noting that as a warning against the file for later reporting.

**Comment by odscjames** [comment]
This seems to have reopened.

To replicate locally, change source to say:

        for page in range(1260, 1270):

**Comment by robredpath** [comment]
I think we can close this, as #187 is pretty comprehensive. We can re-open if there's more issues.
