### ISSUE TITLE
The tool should have an option to clear data for one source_session only out of the DB/Disk.

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#106]
Let's say we have a server with 2 sets of data loaded: A & B.

We want to trash A but keep B.

Currently the only way we have of doing that is trashing the whole DB and starting again - that's not good enough.

**Comment by robredpath** [comment]
Heh, I did wonder about this!

My experience with the scrapers so far has been that it's been the fetch stage that's slow (ie, hours) - the store is relatively quick and painless to re-do (ie, minutes). And, so far, people haven't been doing any intermediate tables or storing results in the database - it's all been queries saved in Redash or personal notes. 

At the moment, I think we're fine to just delete the database and start over regularly; we're very much in the territory of still trying things out and testing them. In the fairly near future, we should expect people to be working concurrently on the server more, and so this becomes more of an issue - I think one of the rules for sharing the server is going to be deleting your data from the db when you're done. 

@odscjames you mentioned on chat that this would be useful for testing scrapers - can you expand on that? Also - do you have a sense of scale for this work?

**Comment by odscjames** [comment]
> you mentioned on chat that this would be useful for testing scrapers

I just thought that part of testing scrapers would be doing a DB load (check encoding errors, etc) and so we may end up with a big DB. If other people are doing analysis at the same time, it would be good to have a easy way to delete part of the DB only.

But it's maybe not high priority to put it in the tool, maybe we can just share some SQL statements here to do that for now (which would help when we finally come to put it in the tool to!)

**Comment by robredpath** [comment]
> maybe we can just share some SQL statements here to do that for now (which would help when we finally come to put it in the tool to!)

Sounds good!

Any idea what sort of size the work here is (hours/days/weeks/months)?

**Comment by odscjames** [comment]
If you mean this clear data tool, very small amount of work.

If you actually mean #100  - ages - I think it was said it took several weeks to download one source and from memory we already know that source has problems and we have to sort it!

**Comment by robredpath** [comment]
I mean the work that you're proposing in this issue - so you're estimating it as hours? Maybe even minutes? 

If it makes #100 easier then by all means go for it.

**Comment by odscjames** [comment]
#108 should contain a useful function in the DB class we can reuse but here's my first quick try at some SQL .... get the ID of the source_session row you want to delete. In one transaction run:

````
delete from release_check where release_id in (select release.id from release join source_session_file_status on source_session_file_status.id =  release.source_session_file_status_id where source_session_file_status.source_session_id = $id);

delete from record_check where record_id in (select record.id from record join source_session_file_status on source_session_file_status.id =  record.source_session_file_status_id where source_session_file_status.source_session_id = $id);

delete from record where source_session_file_status_id in (select id from source_session_file_status where source_session_id = $id);

delete from release where source_session_file_status_id in (select id from source_session_file_status where source_session_id = $id);

delete from source_session_file_status where source_session_id = $id;

delete from source_session where id = $id;
````

Then in one transaction per statement run:

````
delete from data where id not in (select data_id from release union select data_id from record);

delete from package_data where id not in (select package_data_id from release union select package_data_id from record);
````

Not sure how this will work at scale yet but we'll start by assuming the DB is better than what we could do and only look at optimizations later if we need to. We'll properly test and play as we do other work.

**Comment by jpmckinney** [comment]
I haven't read database.py closely, but couldn't we use [ON DELETE cascades](http://docs.sqlalchemy.org/en/latest/orm/cascades.html) instead of manually crafting these DELETE queries?

**Comment by odscjames** [comment]
It could help the first block a lot, but I'd need to check how SA & Migrations worked with that. Also there's an argument to be made that not having "ON DELETE cascades" in the DB makes it harder for people to delete things by mistake - I'd like to check in with peoples feelings on that before going down that route.

**Comment by jpmckinney** [comment]
I'm not clear on people's use cases for deleting rows (besides issues like this one), so it would be good to elaborate those.

**Comment by odscjames** [comment]
>  (e.g. I can't think of a real use case for keeping a release check if the release is deleted).

That implies turning off foreign key constraints, and that's not what I meant at all. I was more concerned that someone might say "Oh, I've messed up something, I'll just delete this file_status row" without realising that a whole bunch of other data is hanging off that. With "ON CASCADE DELETE", what would then happen is it would all be deleted - this is the accidental delete I was referring to. Without, the DB would throw an error and not let them delete it.

> I'm not clear on people's use cases for deleting rows (besides issues like this one)

Well, ideally they shouldn't, but on a shared working server while the software is still in early days and still being developed heavily you can never rule out people needing to tweak things.

**Comment by jpmckinney** [comment]
My understanding of SQL Alchemy's implementation of the [`ForeignKey` class](http://docs.sqlalchemy.org/en/latest/core/constraints.html#sqlalchemy.schema.ForeignKey) is that unless `ondelete='CASCADE'` is specified, then it will do `ondelete='SET NULL'`. More info [on this page](http://docs.sqlalchemy.org/en/latest/orm/cascades.html). I may have interpreted the documentation incorrectly!

**Comment by jpmckinney** [comment]
Moved to https://github.com/open-contracting/kingfisher-process/issues/22
