### ISSUE TITLE
Installation improvement: Database initialization

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher#113]
For database setup, we may want to add a `dbinit` subcommand to the CLI. This might, at minimum, print out the commands to run; or run the commands, collecting any sudo passwords as necessary. 

The CLI doesn't presently implement subcommands, so this may require a refactor so that the Gather-Fetch-Load code is in one subcommand, like `run`, `update` or `collect`.

As part of such a refactor, we may want to move `upgradedatabase` and `dropandcreatedatabase` to separate subcommands, as they are currently arguments that cause all other arguments to be ignored. I was originally confused by the use of `database` in the argument (since they only upgrade, drop or create tables, not databases), so we may want to rename to simply `migrate` instead of `upgradedatabase`, and `flush` instead of `dropandcreatedatabase` (these terms are familiar to Django and other ORM users).

**Comment by odscjames** [comment]
Subcommands have been mentioned before - I agree they are probably a good way to make the CLI clearer.

Just noting if we do Subcommands then I've just added P.R. #105 with a new command and we should include making that a subcommand as part of this work.

**Comment by odscjames** [comment]
Am looking at this now - as we want to add several other options to the CLI, it seems sensible to do this first.

**Comment by odscjames** [comment]
Think this is done in both old and new system, closing
