### ISSUE TITLE
Sphinx docs

### ISSUE THREAD

**Issue by tian2992** [open-contracting/kingfisher#126]
We have some docstrings in place, however, no consistent strategy on building and generating developer / user docs.

**Comment by jpmckinney** [comment]
Please add jpmckinney as a maintainer once the RTD project is created :)

**Comment by odscjames** [comment]
@jpmckinney I have added you to https://ocdsdata.readthedocs.io/ Can you set up the GitHub WebHooks for RTD please?

**Comment by jpmckinney** [comment]
Done!

**Comment by odscjames** [comment]
Thanks!

**Comment by odscjames** [comment]
This is well under way - closing this issue. Specific tasks on pages are already being dealt with on other tickets.
