### ISSUE TITLE
User story: As an analyst I want access to compiled records so that I can perform coverage reviews

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/kingfisher#133]
Our ETL process for BigQuery [included a script](https://github.com/open-contracting/sample-data/blob/d482ebee8f36c21f37bc74316731ab185290c01b/real-examples/merge_releases.py#L15-L26) that generated [records](http://standard.open-contracting.org/latest/en/schema/merging/) by merging individual releases for a given OCID together.

This is important when performing coverage reviews, to be able to check how many unique contracting processes have a particular set of fields etc. 

As records (latest version of everything we know about a process) are conceptually distinct from releases (whatever information was provided in the last update), an analyst should have to consciously choose which they are querying. I.e. we should likely avoid the case when a query would accidentally check **both** releases and records (as this could also lead to double counting problems). 

Suggested solution:

* A step should be added to the pipeline to create merged records;
* This step should be optional (we don't always need it), and possible to run on just a sample of the total data for a given publisher;

**Comment by timgdavies** [comment]
cc @duncandewhurst Does the above cover what we discussed?

**Comment by duncandewhurst** [comment]
@timgdavies, yes thanks

For reference, [this slide](https://docs.google.com/presentation/d/1PymPaa8GD4wKkC3I2mKMFPxFQ81fErgRo9bIbHyZmwQ/edit#slide=id.g3b5834c4d9_0_5) and [this discussion](https://docs.google.com/presentation/d/1PymPaa8GD4wKkC3I2mKMFPxFQ81fErgRo9bIbHyZmwQ/edit#slide=id.g3b5834c4d9_0_5) give some more background on why this is important

**Comment by robredpath** [comment]
@kindly do you fancy doing this?

**Comment by duncandewhurst** [comment]
This would be really useful for some of the work I'm doing on evaluating the NSW Australia data.

I'm trying to check for how many contracting processes a particular indicator can be calculated, based on the presence of a group of OCDS fields, and it would be easier to check that by looking at a single compiled release than by checking whether the group of fields is split across multiple releases.

**Comment by jpmckinney** [comment]
I would like for transforms – like compiling releases, or upgrading 1.0 data to 1.1 data – to be implemented in a generic, reusable way as [described briefly here](https://github.com/open-contracting/ocdsdata/issues/90#issuecomment-394797112).

OCDSKit also has a [very simple implementation](https://github.com/open-contracting/ocdskit/blob/master/ocdskit/cli/commands/compile.py) for compiled releases. However, unlike the script linked from the issue description, it doesn't add any record metadata.

In an MVP, we wouldn't need the following, though it could be interesting to explore later:
* storing a history of transform operations, e.g. a TransformJob that, for compiling releases, might store the name of the Transform, the inputs to the Transform (e.g. the source and any additional filters), any errors, and the dates it was started, finished, etc. (as we have for gather and fetch)
* storing what inputs were used to produce each output within an operation, e.g. a TransformLog that, for compiling releases, might refer to the transform job and store the input (references to specific releases) and the output (reference to specific compiled release)

**Comment by jpmckinney** [comment]
Note: OCDS Kit's compile command now does the same, and more, than the old linked script.

**Comment by odscjames** [comment]
There is now a transform to basically do this in the new system; closing
