### ISSUE TITLE
User story: As an analyst I want simple, visual documentation of the pipeline so that I can understand what is happening at each stage

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/kingfisher#134]
We currently have [a summary of the pipeline steps](https://github.com/open-contracting/ocdsdata/blob/master/ocds-data-pipeline.md) but this doesn't fully detail the steps taken at the level an analyst needs to:

* (a) Understand each step that has taken place;
* (b) Be able to explain this as part of a write-up of analysis

Suggested solution:

* Tim/Rob/James have discussion of the process, and then Tim writes up draft docs, for review by the rest of the team.

**Comment by odscjames** [comment]
Did you have thoughts on how to display the outcome - would this be the start of some Sphinx docs, for instance?

**Comment by odscjames** [comment]
Linking to #126

**Comment by tian2992** [comment]
I think we can also add this to Logging. 
With some clever logging strategies we can even create graphvis dot files and actual pipeline status visualisation for example. #139

**Comment by robredpath** [comment]
@timgdavies @odscjames would this be something there'd be time to do when you're both in Edinburgh next week? Or shall I schedule something for the week after?

**Comment by jpmckinney** [comment]
Not clear that this is still needed so closing. If use case arises again, we can open a new issue.
