### ISSUE TITLE
Australia: Full run has filename errors

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#140]
> ["IntegrityError('(sqlite3.IntegrityError) UNIQUE constraint failed: filestatus.filename',)"]

In about 110 files so far. Always URL's with page in, eg, type-planning-page-2-.json, type-contract-page-124-.json,  type-tender-page-191-.json

From #100

**Comment by odscjames** [comment]
I would like to wait till #154  is merged in first, as that rewrites the run_fetch method and that's probably where we need change things.

**Comment by jpmckinney** [comment]
Metadatabase is gone, so assuming closed.
