### ISSUE TITLE
Convert Old Fetcher:  Uganda

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#16]
https://github.com/open-contracting/sample-data/blob/master/real-examples/uganda/fetch.py

**Comment by odscjames** [comment]
Tags award and contract return 500 errors - how to handle/raise?

**Comment by odscjames** [comment]
> Tags award and contract return 500 errors - how to handle/raise?

This is not true any more - they new return data! See pull request

**Comment by duncandewhurst** [comment]
I have the following command running in a tmux session on the server:

`python ocdskingfisher-cli run uganda`

and in another tmux session I ran:

`python ocdskingfisher-cli status uganda`

but the response seems to relate to an older `data_version`:

> Status for: uganda (Output Dir: uganda, Data Version: 2018-09-18-09-21-48)
> Gather, Fetch, Store and Check all Finished!

I ran `git status` and the server is up to date with the `master` branch.

@odscjames any ideas where I'm going wrong?



`

**Comment by odscjames** [comment]
Talked to @duncandewhurst - have worked out problem (Need to use --newversion when a new run is needed.) Noted that if verbose mode was the default, this would have been obvious. Something to consider in general logging chat?

**Comment by odscjames** [comment]
Yes
