### ISSUE TITLE
Need a better way for CLI users to select runs

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#164]
Currently, there are several CLI situations where the user wants to specify a existing run, and get a clear error if the run they specified does not exist:

   *  run, when looking for an old one
   *  status command
   *  check-different-schema-version command in #162 
   *  #106  - yet to be done
   *  #127 - yet to be done

(Note we do clever things like select the latest version if no version specified to make it easier for them.)

We also have a CLI situation where the user wants to create a new run

  *  run

The problem is:

- There is no clear way to say "no new ones, only existing ones" when creating a Source class which makes for unclear code and a potential source of bugs.
- Across those many different places in the first list we essentially copy and paste code, which means inconsistencies and errors.
- The error messages that a user encounters when trying to do one of the first 5 tasks aren't as helpful as they could be.

It would be good to look at this. Maybe a command to list existing runs on disk could be useful to, as part of a general "how can we make users lifes easier?" question.

**Comment by tian2992** [comment]
Yeah, I just wanted to add, that probably the --run flag should be re-thought as; we do already have the 'run command', specifying sources via --sources might work, however does not solve the ambiguity when specifying more than one.

**Comment by jpmckinney** [comment]
With respect to @tian2992's comment, since there is now a `run` subcommand, it would make sense to remove the `--run` option, and instead accept sources as positional arguments (it's odd to have a required option). We can also rename `--runall` to `--all`. The subcommand can error if both positional arguments and `--all` are present.

**Comment by jpmckinney** [comment]
In general, required arguments in command-line interfaces are positional arguments, not options. So, for the status command, instead of `--source`, it would be a positional argument.

Anyway, I'd be happy for the copy-pasted code to be refactored into the base command class.

**Comment by tian2992** [comment]
#168 would change syntax to ```ocdsdata-cli run all --sample```, ```ocdsdata-cli run uruguay paraguay``` or ```ocdsdata status colombia```.

**Comment by odscjames** [comment]
The new system makes this all so much easier, so I think this problem is basically gone - closing
