### ISSUE TITLE
config.py should be wrapped in a method

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher#171]
As surfaced in #167, `ocdsdata-cli` will error if there's no database config file or environment variable, even though a database isn't needed if e.g. only the gather and fetch steps are being run.

In most cases, importing a Python file shouldn't execute code that has side effects. In this case, the work of calculating the database URL should be done in a method, and other parts of the code needing that URL should call that method.

If we're concerned about efficiency or race conditions, we can have the method use memoization, such that it only performs the calculation once and then returns the cached result for the rest of ocdsdata's execution time.

**Comment by odscjames** [comment]
The new system RHS/Process part always requires a DB now, so this is basically solved. And the new system has DB loading in a func so that imports have no side effects.
