### ISSUE TITLE
Implement an internal API for data transformations/operations

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher#172]
I would like for data transformations, and other operations that have side-effects, to be implemented in a generic, reusable way. This has come up before [[1](https://github.com/open-contracting/ocdsdata/issues/90#issuecomment-394797112), [2](https://github.com/open-contracting/ocdsdata/issues/133#issuecomment-402825867)], and the need for more requirements gathering was recently expressed [here](https://github.com/open-contracting/ocdsdata/pull/162#pullrequestreview-141447291).

Such operations may include:

* CoVE validation (which has the side-effect of storing validation results) (i.e. the 'check' step)
* compiling releases #133
* upgrading 1.0 data to 1.1 data (to avoid having to prepare analyses for both)
* publisher-specific corrections (to avoid analysts having to correct them to run the same analysis)
* database normalization (i.e. the unimplemented 'normalize' step)
* validation using another validator like jOCDS
* pulling in additional data based on external identifiers (e.g. lookup companies on OpenCorporates)

In other words, making this step generic would mean replacing check and normalize with a single step, in which the user decides which operations to run.

In terms of a generic, reusable implementation, we have a base `Source` class for the gather and fetch steps. We can have a base class (e.g. `Transform`) for these operations. A transform would be something that accepts input data, potentially has side-effects like storing validation results, and outputs transformed data (this can be identical to input data if the operation only has side-effects).

----

In an MVP, we wouldn't need the following, though it could be interesting to explore later (though, if they can be implemented in the first iteration, all the better):

* storing a history of operations, e.g. a `TransformJob` that, for compiling releases, might store the name of the Transform, the inputs to the Transform (e.g. the name of the source and any additional filters), any errors, and the dates it was started, finished, etc. (as we have for gather and fetch)
* storing what inputs were used to produce each output within an operation, e.g. a `TransformLog` that, for compiling releases, might refer to the transform job and store the input (references to specific releases) and the output (reference to specific compiled release)

That way, we'll have provenance for the outputs of transformations.

----

With respect to compiling releases, OCDSKit also has a [very simple implementation](https://github.com/open-contracting/ocdskit/blob/master/ocdskit/cli/commands/compile.py) of compiling releases. However, unlike the script linked from the issue description in #133, it doesn't add/invent any record metadata.

**Comment by jpmckinney** [comment]
Regarding the use of disk space, a few things can consume space:

1. the transformed data
2. various side-effects
3. the history of operations

## History of operations

I think we want (3) because tracking provenance is generally good in data work, and it shouldn't consume much space, as it will refer to data on disk i.e. it wouldn't make a copy of input data; it would simply store enough information to identify the input data.

*Aside*: The metadata DB stores part of this provenance history. At present, are records ever deleted from the metadata DB? If so, we may need to think through when and how to preserve that part of the history.

*Aside*: Another good thing in data work is replicability. To guarantee replicability, we'd need to make a copy of the input data, e.g. to protect it from deletion if a user deletes a session. However, for this issue, I'm not concerned with replicability; whether we pursue replicability is a separate discussion.

## Side effects

(2) isn't specific, but presumably, if we're running an operation for its side-effects, we want those side-effects and are happy to pay the cost of disk space.

## Transformed data

For (1), in cases where the transformed data is different from the input data, the same reason as (2) applies.

In cases where the 'transformed' data is the same as the input data (e.g. as in validation), we'd rather not consume additional disk space.

I see a couple ways of avoiding consuming disk space (which perhaps need to be used in combination), which I haven't fully thought through:

1. Treat transformed data as simply another side-effect. In other words, a default 'transform' is a no-op, void method. As such, there'd be no expectation/requirement to write its output to disk.
1. The transform classes would, in all cases, refer to data, instead of copies of data. In an operation transforms data (e.g. 1.0 to 1.1), it would write the transformed data to disk, and then refer to it as the output in the history. If it doesn't transform data (validation), it would write nothing to disk, and then refer to the input as the output in the history.

**Comment by jpmckinney** [comment]
I would like to point out that, at present, there is very little within this framework that ties it exclusively to OCDS: the exceptions are the individual sources, the checks step, and the analysis step (which will always be specific to whatever data). There is an opportunity to move individual sources to a separate repository and rework the checks step as described here to make this a generic framework for any data. For example, ODS would perhaps like to implement sources for 360Giving, etc.

On one hand, such frameworks are common and the world may not need another ([I've made my own, for example](https://github.com/jpmckinney/pupa-ruby)), and there are benefits to having the freedom to add OCDS-specific logic to ocdsdata. On the other hand, it looks like, with a little effort like in this issue, we can avoid specific logic. Anyway, this is hopefully something to inspire the work on this issue.

**Comment by odscjames** [comment]
There was discussion at Montreal and we think we have a plan for this.

Basically, a load of data creates a new entry in the source_session table.

A transformation of that will create a new source_session entry. The new data will then be loaded in the existing tables (eg record , release, etc) - no changes will be made to existing tables. This way, all anaylsts queries will work with no changes.

New columns on the source_session table will track that a transform happened, and what it was.

Source Session Table Changes:

- source_id NULLABLE
- data_version NULLABLE
- sample NULLABLE
- add translated_from_source_session_id   NULLABLE
- add translation_id  Text - an string ID like source_id
- add translation_details JSON 


We already have disk space saving stuff in the data and package_data - we think this will continue to work.

It is noted that some other work needs to be done before this can be looked  at; namely sorting out the thing about sessions split across disk and DB. See #170 #199 and others for more.

**Comment by jpmckinney** [comment]
Are the 'translation' columns meant to be 'transformation' columns?

**Comment by odscjames** [comment]
Yes, thanks. Edited.

**Comment by odscjames** [comment]
This is in the new system, closing
