### ISSUE TITLE
Delete or PR stale, single-commit branches

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher#180]
https://github.com/open-contracting/ocdsdata/branches/all

* gather-and-fetch https://github.com/open-contracting/ocdsdata/commit/3c32c7f3c913f75ad9810f28c959a0a4c8f2b716
* sql-scripts https://github.com/open-contracting/ocdsdata/commit/9d54401b2bc4e5c853144c5606d3ccc85ed94042
* non-null-db-recordcheck https://github.com/open-contracting/ocdsdata/commit/408c3ebaf111a9829e4f01fe14767e85ea408c8f

**Comment by odscjames** [comment]
> gather-and-fetch 3c32c7f

Pretty sure this can be deleted - it's been superseded by other code. @kindly ?

> sql-scripts 9d54401

Not so sure about this one - this might be the root of something we were looking at? @kindly  ?

> non-null-db-recordcheck 408c3eb

This work has already been done elsewhere - deleting.

**Comment by jpmckinney** [comment]
There are several (old) non-PR branches – please either delete them or open them as PRs against the relevant repo.

**Comment by jpmckinney** [comment]
https://github.com/open-contracting/kingfisher/branches
