### ISSUE TITLE
Move basedir config from command line flag into config file/env var like DB config?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#182]
Currently it's odd in that we have:

  * DB config, set in config file / env vars
  * basedir config, must be passed as command line option to all relevant commands

Both of these config options are really the same in that they are things you need to pass every time you use it.

Also, they should be changed together - if a user has 2 DB's they should also really have 2 data dirs, and make sure they are used together. Using DB A with Data Dir B would be weird.

Another problem is that it would be to easy to forget to pass the basedir option when running random commands.

Let's move basedir config from command line flag into config file/env var, like DB?

(Note this would make #164 a bit easier.)

**Comment by jpmckinney** [comment]
I only just noticed that the default `basedir` is a `data` directory in the same directory as ocdsdata.

In most scraping/ETL frameworks I've used, the default is a `data` directory in the current working directory. It's possible for users to just run gather and fetch, if all they want is data, and in that case, they probably want the data to be easily accessible, e.g. in the current working directory. Is there a preference for the default `basedir` to be somewhat inaccessible to users?

Why should there be a 1-to-1 relationship between databases and data directories? If a user is only interested in getting data into the database for analysis, then the data directory is just temporary storage, which they can delete after loading. It wouldn't be relevant to store, in a configuration variable, its long-term location.

On our own deployment, I can see some reasons to ensure users aren't creating data directories all over the place (if we were to change its default to the current working directory). We can either: have instructions to e.g. change into the proper directory; put the data directory in the home directory, which is the default directory people sign in to; or have some rarely-used config file/env var override that other users shouldn't have to worry about.

What do you think?

**Comment by tian2992** [comment]
I think /data is a reasonable default, however that should too be a settable variable for flexibility in workflows.

**Comment by odscjames** [comment]
Thanks for comments - now some work has come up that means I should look at this again. 

(We are ending up copy and pasting the code that sets the default to several different places, which isn't good. So we should centralise that.)

My preference is to move this into the config file.

I understand James's point about "Why should there be a 1-to-1 relationship between databases and data directories?". However, we currently have a situation where there is often a relationship (tho I am working to break that). And I would also say that being able to support 2 or more data directories is an advanced scenario that we shouldn't worry about to much now.

I think it's much more likely that one user would run commands specifying a different data directory but then forget that a week later, and waste time and energy working out why things weren't working, where the work they did last week has gone, etc ... and a config file would avoid that.

Also, assuming the user does change the directory, they need to remember to pass it to certain commands. But not all commands! Only some. And some commands that do need that option, don't have it, so they can't be used yet. So that's a right pain. (If we aren't going to move this to a config file, we should at least make this consistent by moving to "python ocdskingfisher-cli --basedir /data run  taiwan" ie, a consistent option before the sub command)

This would also allow sys admins to set the location of the data folder without having to tell all users to remember to be in the right directory or pass a special option - I'm thinking of our server here.

Also, sometimes I check out code into different folders to fully test sources before merging to master. Doing this and making sure all the data stays in the same directory would be easier with the config file.

I think there is no "right" answer here - there are several different ways to do this. So I'm just picking a direction and going with it. I think moving to the config file is the better option for our current uses, and it does continue the use of the config file we have already established.
 



ps. On the point of changing the default from the code directory to the current directory, I'm not fussed as long as we do the config file thing first :-) If not, want to discuss how to educate users. I can certainly see the point that code directory is an odd place to put it - it was just our first choice, and I don't think we discussed it at the time.

**Comment by jpmckinney** [comment]
I'm happy with the proposed config direction.

Can issues be created for some of the other points, e.g.

* changing the default to the current directory (not the code directory, where people can accidentally stockpile GBs of data on small disks without knowing it)
* having `--basedir` as a common option for all relevant commands
* having a single place in the code for determining the base directory

For the commands that wouldn't have a `--basedir` option (I haven't checked which those might be), if a user might reasonably expect them to have this option, then we might want to add some docs to explain why the option is missing.

Regarding the implementation of a common option that some subcommands don't have, in csvkit, the pattern is for those subcommands to opt-out of those options (see [common options](https://github.com/wireservice/csvkit/blob/master/csvkit/cli.py#L131) and [opting-out](https://github.com/wireservice/csvkit/blob/master/csvkit/utilities/csvcut.py#L21)).

**Comment by odscjames** [comment]
> having a single place in the code for determining the base directory

This I'll do as part of creating the config option under this issue.

Others are:

https://github.com/open-contracting/kingfisher/issues/223
https://github.com/open-contracting/kingfisher/issues/224
