### ISSUE TITLE
Add "Scotland" source

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#186]
https://www.publiccontractsscotland.gov.uk/
https://www.publiccontractsscotland.gov.uk/NoticeDownload/Holding.aspx

In a few weeks, hopefully

**Comment by odscjames** [comment]
1)

https://api.publiccontractsscotland.gov.uk/v1/Notices?dateFrom=2016-10-01&noticeType=2&outputType=1
and 
https://api.publiccontractsscotland.gov.uk/v1/Notices?dateFrom=2005-10-01&noticeType=2&outputType=1

Both return the same data!

My Guess is that if you put a dateFrom that is to early they silently go "That's a silly date - we'll ignore it!" and then default you to today's date.

Is it possible to ask for an error to be returned instead? That would really help people using the API!

2) 

"You may only retreive notices which are up to a year old."

Is there any chance this is going to be expanded? 


3)

"Please note that not all form types are available in all formats. These will be made available by the end of September 2018."

Also, we can look at this now but we'll have to come back to this over the next month anyway.

**Comment by timgdavies** [comment]
Interesting to see. Have we worked out how to get that API to provide JSON? 

I can only get XML that looks kind of like OCDS, but I've not managed to get JSON

This might be something for us to do some engagement on before we try and get a scraper working?

**Comment by odscjames** [comment]
There is ongoing conversations with Scotland about the state of their API, so this may come back. But there is nothing now, so let's close.
