### ISSUE TITLE
Review Mexico scrapers

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#190]
@yolile reports that the publisher sends new links via email regularly but we've not been able to ascertain a programmatic way of getting the latest data. It may or may not be the same data as we get via the current API URL - we should compare.

**Comment by robredpath** [comment]
Also - inai and CDMX - may have updates that require changes to the scrapers

**Comment by robredpath** [comment]
Also - found reference to "Ministry of Communications Telecom PPP" in the CRM - but couldn't find any data

**Comment by jpmckinney** [comment]
I don't think there's any presently available data for Ministry of Communications Telecom PPP

**Comment by jpmckinney** [comment]
Closing in favor of linked issues.
