### ISSUE TITLE
Add Chile scraper

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#191]

**Comment by robredpath** [comment]
https://desarrolladores.mercadopublico.cl/docs/services/5a9ed02f718ed712f4403e75/operations/5a9ed1fc718ed712f4403e78

**Comment by odscjames** [comment]
Year 2008 onwards

**Comment by odscjames** [comment]
@yolile  will check on the first full run of this scraper

**Comment by yolile** [comment]
The first full run crashed, see #241

**Comment by yolile** [comment]
@odscjames  The error is that some json files have: 

`{  "NumeroError": -2146233079,  "Mensaje": "The operation has timed out"}`

instead of a release-package

**Comment by odscjames** [comment]
If it's timed out does that mean it's an intermittent error? In save_url function, could we look for "NumeroError" and retry a few times?

**Comment by jpmckinney** [comment]
Closing in favor of linked issue.
