### ISSUE TITLE
Add Honduras scraper

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#192]
@duncandewhurst - can you let us know about the data for CoST Honduras

**Comment by odscjames** [comment]
That appears to only have 20 records - is that right? Am I missing some paging options - or, when more records are added, will there be paging?

Still, if that is it that will be easy to do at least :-)

**Comment by duncandewhurst** [comment]
That's in the right ballpark, it's PPP data so tends towards a small number of big contracts, rather than lots of small ones, though when I ran it through the validator, that reported 21 records.

**Comment by odscjames** [comment]
For now, may have to revisit later when more data. But can close now.
