### ISSUE TITLE
Add Zambia scraper

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#196]
https://www.zppa.org.zm/ocds-data (note: website is slow, not broken). Also - publishes both records and record packages - not yet checked if the information is the same(!)

**Comment by odscjames** [comment]
Update https://github.com/open-contracting/ocdsdata/blob/master/docs/sources.rst to!

**Comment by odscjames** [comment]
@duncandewhurst Do you have any idea why 2017 - April is missing?

**Comment by duncandewhurst** [comment]
No idea I'm afraid, although I don't think they started publishing properly until later in 2017 so it may not be important.

I think there is an API of sorts underpinning the packages you can download through the website, I found this note from when I looked at it around this time last year;

> there is an API endpoint to retrieve a package of all the releases for a given ocid, ([example](https://www.zppa.org.zm/ocds/services/releasepackage/getfullreleasepackageforocid/ocds-23g63a01-115211))
there is an API endpoint to retrieve a monthly bulk file of record packages ([example](https://www.zppa.org.zm/ocds/services/recordpackage/getrecordpackage/2017/6))

I'm not sure how I found those though
