### ISSUE TITLE
Write demonstration script in /bin

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#2]
The work here is to write and maintain script(s) in /bin that make use of, and serve to demonstrate the functionality and expected usage of the ocdsdata library. 

This will be hard to call Done, as it's a moving target. During development, the expectation is that this script will be updated alongside tests and the library itself.

**Comment by jpmckinney** [comment]
If the goal of this issue is for demonstration, would a notebook, Markdown file with code blocks, or [Pycco](https://pycco-docs.github.io/pycco/) page, etc. be better?

**Comment by robredpath** [comment]
This started off as a way to get the library into use and to serve as a demonstration for how to use the library. However, over the course of the co-working, the ocdsdata-cli script became the main focus for development, as it put the tools that the analysts there needed in their hands as quickly as possible. 

I think that as and when the library is likely to be used by people outside of ILDA/ODSC/OCP, demonstrators will be really useful. Until then, I feel it's less of a priority.

**Comment by jpmckinney** [comment]
Sounds good!

**Comment by robredpath** [comment]
As the tool has evolved, a lot of the focus has been on the cmdline tool rather than the library aspects (although we've been careful to ensure that the code can still be used as a library). Closing this issue.
