### ISSUE TITLE
Might need a better name for "Sessions"

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#200]
A session, or source session, is currently a set of data got running a source at a particular time and in sample mode or not.

So for one source (eg UK) a server may hold

- UK, 2018-04-01-10:00:00, Sample
- UK, 2018-04-01-12:00:00, Not Sample
- UK, 2018-10-01-12:00:00, Not Sample

In the future, a "session" could also mean:

- A set of data that has been transformed from a source in some way  #172
- A set of data loaded locally #173 

At Montreal some people noted that this is now a terrible name and it should be changed. No decision was reached on a new name.

Other people noted that it would be a lot of work to change it and we should just leave it.

It was noted that changing it sooner rather than later would be better.

**Comment by jpmckinney** [comment]
Naming is important, so I prefer to fix it. As I understand we have decent test coverage, so is it significantly more work than find-replace in the code, and then database migrations to rename tables and columns (which should be fast operations, I think)?

**Comment by robredpath** [comment]
Currently, aren't these called 'versions'? This morning I wanted to get a sample of the chile_compra data while leaving the main scrape running, so I ran the command with --newversion.

**Comment by odscjames** [comment]
> Currently, aren't these called 'versions'? This morning I wanted to get a sample of the chile_compra data while leaving the main scrape running, so I ran the command with --newversion.

I guess we called that option versions as the thinking was you were getting a new "version" of data from a  particular source. So they are not called "versions" overall but that word is used. Good to note, that option should probably change to.

Ok, lets look at possibilities for a new name then  - how succesful we feel we are with this will help us decide whether to rename or not. 

"Data Set" is the obvious thing maybe - that is a general term, but it is a general concept. Could that be confused with anything else here?

**Comment by jpmckinney** [comment]
In the open data community, dataset is typically used to describe a resource within a data catalog, which can change over time. Session is about data at a specific point in time. Would 'snapshot' be appropriate?

**Comment by odscjames** [comment]
'snapshot' is good in some ways but bad in other ways - for a source that takes 9 hours to fetch, you might end up talking about "resuming the snapshot half way through" which might be confusing as snapshots are usually thought of as instant things! Hmmm .... not sure.

**Comment by odscjames** [comment]
Maybe something like "Data Pool"?

You create a new "Data Pool" and it might take weeks to fetch all the data into it .... You can list "Data Pools" and see the status of a particular "Data Pool" .... A "Data Pool" might be on disk or in the DB, or in the process of being copied from the former to the later .... You can take a "Data Pool" and perform some transformation on it that gives you a new "Data Pool" ....

**Comment by jpmckinney** [comment]
I'd prefer to avoid neologisms. I think there are likely terms from library and archival science (and especially from web archival) that we can re-use to find a term like 'snapshot' that avoids the connotation of being instant. I haven't done exhaustive research, but a term that comes up frequently is 'capture' (by a crawler).

**Comment by odscjames** [comment]
Someone suggested jokingly we name it after a fish.

https://www.rspb.org.uk/birds-and-wildlife/wildlife-guides/bird-a-z/kingfisher/breeding-feeding-territory/ says "Kingfishers eat mainly fish, chiefly minnows and sticklebacks"

I'm voting Minnow, mostly for: "Has that minnow finished downloading yet?" "No, another 2 weeks probably" :smile: 

Or, I think "capture" is good. Might be slightly odd when talking about transforms "Make a new capture by transforming this old capture" but I think it would be clear enough.

**Comment by jpmckinney** [comment]
I prefer to keep internal concepts as clearly named as possible :)

In documentation, we could maybe find another name for a transformed capture, but in code it might just be another instance of a capture. I suppose, strictly speaking, we are transforming the data within a capture, and storing it in a new 'capture'.

Other generic term could be 'collection' – 'collect' is a synonym of 'capture' (v), but 'collection' has much looser semantics, such that making a new collection from an old collection doesn't raise eyebrows.

**Comment by odscjames** [comment]
I'm happy with "collection" - others?

**Comment by timgdavies** [comment]
Overall I prefer 'session' to 'collection', and as mentioned in Montreal, I'm happy with the term 'session' if we use if consistently (e.g. --newsession rather than --newversion) and explain the concept we are using it for. 

However, if we are changing, consider 'instance' rather than 'collection'. 

E.g:

>  Start a new instance of the UK data. 

> This is an instance of the UK data 

> Check what we have in the instance of the data from September

**Comment by jpmckinney** [comment]
I'm not sure session or instance address the concern in the issue description, about choosing a term that is appropriate to both captured data and transformed data.

**Comment by odscjames** [comment]
Although a few other suggestions have been made, we seem to have general acceptance of "collection" and nothing else has gained support. So unless anyone vetoes very soon, I'll go with that.

**Comment by odscjames** [comment]
cli-run in the docs could do with some updating, and there are probably other docs - leaving open for that.

**Comment by robredpath** [comment]
Moved into #253
