### ISSUE TITLE
Proposal: Rename tool to 'Magpie'

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher#202]
As mentioned at the retreat, 'ocdsdata' is a terribly confusing name. I propose 'Magpie'. (Magpies are birds that collect things for later. Squirrels also collect things, but I prefer the image of a magpie.) There is no major software project named Magpie, and none in our domain, so it's okay to use.

More people are becoming aware of the tool, so we need a name that will not be confused with actual 'OCDS data'.

I propose that unless anyone comes up with a better name by Friday, August 24, that we rename the repository to 'magpie' and update all references to 'Magpie'.

----

Total suggestions thus far:

* magpie
* pica pica
* ODP (OCDS Data Pipeline)

**Comment by jpmckinney** [comment]
Other animals that hoard, etc.:

* bowerbird (not a well-known animal, not obvious to spell)
* other corvids besides magpies
* other rodents like hamsters

**Comment by timgdavies** [comment]
I have a slight cautious of going for a particular corvid as the name, as I'm aware different birds have different social significance around the world (See section on folklore associations of the Magpie in https://en.wikipedia.org/wiki/Eurasian_magpie).

A slightly more cryptic alternative may be the scientific name, 'pica pica'?

**Comment by robredpath** [comment]
At the retreat, I definitely felt the weight of the name - so +1 to renaming. Two things, however: 
- One of the main developers of ocdsdata is on vacation until after August 24th, so I'd propose an extension of the deadline to the 31st so that everyone has a chance to contribute to the discussion
- There's a mobile data collection app called Magpi, which might be suitable for some community contract monitoring applications, so I'd be cautious of that particular corvid. 'pica pica' is a good suggestion, but we should be aware that Pica is an eating disorder. My suggestion would (unfortunately) be a TLA - ODP (OCDS Data Pipeline), and the tool being odp-cli.

**Comment by jpmckinney** [comment]
'pikapika' is also the sound Pikachu makes…. It depends how strong the social significance is. If we were to call it Raven, for example, I don't think the parts of the world that associate ravens with evil (which includes North America), would somehow associate the software with evil.

At the other extreme, Mosquito wouldn't be a good name, because no one likes mosquitos.

**Comment by odscjames** [comment]
I can understand the motivations behind wanting to rename (data is a very general word) and also the motivation for picking a non descriptive name (so our "OCDS validator" is not THE "OCDS Validator" when other people write other ones, and so there are less problems when the purpose changes over time  [These 2 reasons taken from CRM] ).

Specifically for this repository, I don't think I have any clever ideas about bird names at the moment, tho I'm generally a fan of them.

However, given the second set of reasons, might this not kick off a slow round of renaming, maybe one at a time or when we create new projects? Do we want to think of a theme of names - such as other animals? (Tho O'Reilly have kinda done that one) I think it would be good to discuss this in advance - I worry that if we just rename this one repo now we'll end up going down a "Rename all the things!" road later without really discussing it first.

![Rename all the things](https://memegenerator.net/img/instances/63138556/rename-all-the-things.jpg)

**Comment by jpmckinney** [comment]
The discussion has mainly occurred in CRM issue 3650, so I'll close this to avoid confusion and to re-centralize conversation.

**Comment by jpmckinney** [comment]
Regarding a runaway renaming of all things – I'm responsible for OCDS products/tools, and I don't expect to do a rash of renaming. I'd either do one at a time, or have a longer discussion around a comprehensive scheme or process for naming tools.

**Comment by jpmckinney** [comment]
The leading bird name is Kingfisher, so please contribute to issue 3650 by end of day tomorrow if there's a preference for another name.

**Comment by odscjames** [comment]
Reopening to use this issue to discuss practical steps.

Firstly, the repository in itself should be renamed on GitHub. This in itself won't cause major disruption; people will have to update their Git remotes (and the Git remote on the server) is all. (Will Travis CI follow automatically or will this need tweaked?) So maybe we can try and do this next week; maybe @jpmckinney could do this last thing Tuesday, and check Travis? (I'm away Monday & Tuesday but can then do the remotes on the server on Wed )

The next and bigger step is to rename the contents of the repository and associated things:
- the URL and name of the read the docs site and the link in readme
- the name of the Python package
- any instances of the name used in the README, comments and docs
- update setup.py

Renaming the Python Package will cause merge conflicts for most Open Pull Requests and current work in progress, so I want to get as many of them merged as possible, then check with other programmers that they aren't in the middle of something.  And then I'll do this work in one go (making sure someone is standing by to check my pull request). I can schedule this in after the repository renaming has happened.

Then there is user accounts, DB's, etc on the existing server - these will be looked at last. (We may decide to leave them.)

**Comment by jpmckinney** [comment]
@odscjames I've renamed the repository - the other steps sound good!

**Comment by odscjames** [comment]
@jpmckinney I made you an admin on https://readthedocs.org/projects/ocdskingfisher/ - can you set up the web hooks between this repo and that project? Thanks.

**Comment by jpmckinney** [comment]
I deleted the https://readthedocs.org/api/v2/webhook/ocdsdata/44014/ webhook and added that one, which is set to run on pushes and PRs – let me know if that's the configuration you want.

**Comment by odscjames** [comment]
@jpmckinney Just seen an update on RTD fine - thanks.

I think that might be this issue done now :-) Re-open if not ....

**Comment by jpmckinney** [comment]
🎉
