### ISSUE TITLE
Add Bandung scraper

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher#203]
There is an API endpoint which returns a list of contracts by year:

https://birms.bandung.go.id/beta/api/contracts/year/2016
https://birms.bandung.go.id/beta/api/contracts/year/2017
https://birms.bandung.go.id/beta/api/contracts/year/2018

Each contract has an uri which leads to an OCDS release, e.g.

https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-s-2016-5022700

Currently the releases aren't wrapped in a release package, but this [may change soon](https://github.com/OC-Bandung/newbirms/pull/22)

This looks like it is work in progress but it would be great if we can use ocdsdata to give feedback

**Comment by odscjames** [comment]
So for each uri - eg https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-s-2016-5022700 It's just a straight release. We'll have to add a new release option to data_type but that should be fine.

Note there is paging on https://birms.bandung.go.id/beta/api/contracts/year/2016 but it looks fine.

No problems anticipated.

**Comment by mpostelnicu** [comment]
howdy,

we've just merged https://github.com/OC-Bandung/newbirms/pull/22 into master, it will be deployed soon and it will provide package metadata. I also validated this with the OCDS validator and it passes just fine

new URLs available
get packages for each year: `/api/packages/year/[year]`

example for 2016 https://birms.bandung.go.id/beta/api/packages/year/2016

This will link to OCDS compliant package metadata, along embedded releases

example package URL
https://birms.bandung.go.id/beta/api/package/ocds-afzrfb-s-2016-3662192

**Comment by duncandewhurst** [comment]
thanks @mpostelnicu!

**Comment by odscjames** [comment]
Work needed on scraper: Change /contracts/ to /packages/

**Comment by mpostelnicu** [comment]
change deployed to prod, so now u can see it online ! http://birms.bandung.go.id/beta/api/packages/year/2016

**Comment by mpostelnicu** [comment]
@odscjames all contracts were validated against OCDS schema and no more 500 errors. please re-restart the scrapper.

thanks

**Comment by duncandewhurst** [comment]
@mpostelnicu are any further updates to the data planned or would this be a good point for the helpdesk to review and provide feedback?

**Comment by mpostelnicu** [comment]
@duncandewhurst  no further changes are planned soon, so i think it is a good time to take a look.

**Comment by jpmckinney** [comment]
Is this closed by #245?

**Comment by odscjames** [comment]
Yes
