### ISSUE TITLE
Add digiwhist scrapers

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/kingfisher#207]
The DigiWhist project has been capturing contracting data from all European Countries, and has converted this to OCDS format with bulk downloads available at https://opentender.eu/download

These files are provided as zipped JSON Lines files. 

In terms of use of ocdsdata/kingfisher for data analysis (as opposed to just validation), have scripts for the import of all of these datasets would be super useful.

**Comment by timgdavies** [comment]
We could either (a) load all of this into a single 'digiwhist' session, or alternatively, (b) have a base scraper that we then subclass for each country, so that there is 'digiwhist_austria', 'digiwhist_belgium' etc. in the database.

**Comment by odscjames** [comment]
> (b) have a base scraper that we then subclass for each country, so that there is 'digiwhist_austria', 'digiwhist_belgium' etc. in the database.

Given size, I'm going for this option. 

Need to think about this tho - this is the first time we have dealt with the JSON Lines format.

**Comment by odscjames** [comment]
I've checked some countries at random, and it always seems to be JSON Lines of Release Packages. Do you know if it is always Release Packages, or do they use something else at other times?

Thanks

**Comment by odscjames** [comment]
Ouch, just realised it's going to be impossible to do sample mode for this source in a meaningful way. Not sure how to handle - whether to just silently do full download, or raise an exception. The latter would cause problems for people running "run --sample --all" so maybe the former for now?

**Comment by jpmckinney** [comment]
@LindseyAM is interested in checking whether the Digiwhist data is structurally correct (not a deep review, just a yes/no 'does it validate?'). I see the AT file fails. Do other files pass? cc @duncandewhurst

**Comment by odscjames** [comment]
I just tried running all countries, and I got crashes on almost all of them: Iceland, Serbia were some of the few that didn't crash. I've put in a thing to ignore the crashes and they are now running on the server.

**Comment by jpmckinney** [comment]
What's the reason for a crash?

**Comment by jpmckinney** [comment]
Closing in favor of linked issue.
