### ISSUE TITLE
Syncing and keeping up to date main ETL server installation

### ISSUE THREAD

**Issue by tian2992** [open-contracting/kingfisher#215]
Our main ETL server needs to be constantly upgraded in order to keep in sync with the latest of master branch. This issue is to discuss the approaches to achieve this.

**Comment by odscjames** [comment]
I think this happens every Thursday anyway, during normal server upgrade. Will check up on details.

**Comment by jpmckinney** [comment]
We should at least document how the deployments get updated – in particular without interfering with running scrapers / operations.
