### ISSUE TITLE
force-fetch-to-store fails when fetch done but with errors

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#252]
-    Fetch finished, but with errors
-    Store won't run cos of errors
-    Users tries to use force-fetch-to-store but it just says "Fetch is already finished; there is no need for this!"
-   User is stuck
-   User is sad

This case is blocked by the tool - need to look into this.

**Comment by yolile** [comment]
This happens to me sometimes. (and makes me sad) My workaround is edit the metadata.sqlite3 file deleting the rows with fetch_success = 0 and then run again.

**Comment by odscjames** [comment]
This command doesn't exist in the new system. Closing
