### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#253]
As I've been reviewing issues and bits of comms around Kingfisher, there's been a few documentation needs that have come up. These might want to be split up later, but for now, this helps clean things up!

- Now that we're starting to see more external use, the README could do with revisiting. More overview of what the tool does and what use cases it can help you with. Reinforce that it's modular. 
- Consistent use of the term "collection" instead of "session" - from #200
- Providing more example commands/queries for parts of the docs that not all of our potential users will be confident in - such as on https://ocdskingfisher.readthedocs.io/en/master/requirements-install.html where we say "You need to create a UTF8 Postgresql database and create a user with write access." - where some examples might help!

**Comment by odscjames** [comment]
Closing as new system means different docs needs
