### ISSUE TITLE
Some kind of web interface

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#254]
During August 2018 trip, it turned out both me and @yolile had been wondering about some kind of read only web interface, to make it easier for people to see what's on the server and browse bits of the data.

(Technically, my thoughts were a Flask app, as we can use our existing database stuff with that easier.)

Discuss. I think the first goal would basically to replicate the status command, and then provide lots more info on that (what happened to parts of a fetch process is a question I've had to answer for others before, and that could just be in this)

**Comment by yolile** [comment]
Maybe we can also include some basic queries, as:
- List of collections with dates
- List of publication policies of each publisher
- List of publishers/collections that are valid
- Sample of publisher data

I think this could be a great task for @romifz

**Comment by jpmckinney** [comment]
Can't we use Redash for those basic queries? What is the need for replicating them?

**Comment by odscjames** [comment]
While Redash can be used, it requires a bit of domain knowledge to interpret the results.  With a web UI, we can provide really clear to follow information. 

Also, Redash doesn't have a public access (I think) and even if it did, not sure I'm happy making that public - even with a read only DB connection, it would be easy to cause trouble on a DB server. 

Anyway, closing here - made an issue in the new system repo for future discussion
