### ISSUE TITLE
Transformation to upgrade from 1.0 to 1.1

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher#256]
I'm about to delete this script from the sample-data repository (it doesn't belong there), so wanted to provide a link to it here.

https://github.com/open-contracting/sample-data/blob/6a3e03ff17afa35ab8f93def1cc481c8170d8b5b/fictional-example/update_1_0-1.1.py

There is another script here. I haven't looked at the differences:

https://github.com/open-contracting/sample-data/blob/d482ebee8f36c21f37bc74316731ab185290c01b/real-examples/update_to_v1_1.py

* Adds amendment handling

**Comment by odscjames** [comment]
There is a basic transform in the new system, closing
