### ISSUE TITLE
User story: As an analyst I want to load non-OCDS datasets into the database

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher#267]
To support hack days around contracting data in the UK we had loaded the following datasets into Google Big Query, so that participants could connect contracting data with other types of data:

* Contracting data (OCDS format)
* Spending data (from SpendNetwork)
* Grants data (360Giving format)
* Company data (from Companies House)

Other types of data that it would be useful to have in the same database as OCDS data include beneficial ownership data and budget data.

It would be good to run future hack days using Kingfisher and more broadly these are the types of data which users of Kingfisher might want to connect to contracting data, so some documentation on how to load other datasets into the Kingfisher database would be useful (recognizing that some degree of customization will be required for each dataset)

**Comment by jpmckinney** [comment]
There exist tools for loading arbitrary data into SQL databases. I don't think Kingfisher ought to become that sort of general solution. In any case, let's postpone to a future sprint.

**Comment by duncandewhurst** [comment]
This wasn't a request to do it in this sprint, also the request was for documentation, such as pointers to other tools, rather than necessarily implementing a general solution in Kingfisher.

**Comment by jpmckinney** [comment]
Please open a corresponding issue in the CRM, as this issue is not specific to Kingfisher.
