### ISSUE TITLE
[2.1] OCDSKit - release->compiledRelease functionality - make a function or class

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#268]

**Comment by kindly** [comment]
I have made a pull request to ocds kit for the absolute minimum library functions needed for kingfisher.
https://github.com/open-contracting/ocdskit/pull/80

This covers point 1. above but needs a version not on pypi to work.

As to point 2:

I think this functionality should be part of the cli and not the library as the library should not really be aware of the JSON streams.  Whatever happens with this, at least all the `ocids` will need to be cached, so you can pick up if there is a *gap* for a particular ocid or you will need to just trust the input is sorted.  The dates being ordered is not necessary as ocdsmerge currently forces order on release date anyway.

**Comment by jpmckinney** [comment]
Re: 1: Unless you are passing a dict as the schema to OCDS Merge, it will cache the merge rules on its own, so that optimization is no longer needed in OCDS Kit or other tools.

Re: 2, I'll open an issue on OCDS Kit to explain better.

**Comment by robredpath** [comment]
We're no longer planning to use OCDSKit to do the merging, so closing.
