### ISSUE TITLE
Set up version control for new code

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#270]
This ticket is to agree names and git repositories - proposal below.

The name "Kingfisher" will continue to be used to refer to all parts of the tool.

This repository - https://github.com/open-contracting/kingfisher - will hold the overall docs for the whole tool, and hold incoming and existing issues. 

To refer to the two halves, the names "Kingfisher - ????" and "Kingfisher - ?????" will be used.

Two new git repos https://github.com/open-contracting/kingfisher-??? and https://github.com/open-contracting/kingfisher-??? will be created to hold each half. Having separate repos:

- enforces separation between the two halves
- allows independent release tags
- Means that with git commit history, branches, changelogs, etc it's easy to know if something is relevant to the half your interested in
- if your working on a branch on one half, less problems keeping branch up to date due to changes in the other half
- allows Travis tests that target just that half (with a different set of install requirements for each half) leading to faster Travis

**Comment by jpmckinney** [comment]
Sounds good to me. If using the ETL metaphor, then perhaps `kingfisher-extract` and `kingfisher-load`. (Not sure where transform lives until #269 is resolved.)

`crawler` is usually used in the context of web indexing, so an alternative is `kingfisher-scrapers` and `kingfisher-processors`.

**Comment by odscjames** [comment]
How about slightly simpler typing - kingfisher-scrape and kingfisher-process? :-)

**Comment by odscjames** [comment]
We now have https://github.com/open-contracting/kingfisher-process and https://github.com/open-contracting/kingfisher-scrape

Before we start to use them, can @robredpath turn on Travis and lock down Master branch as usual? (I don't have rights for that)

**Comment by odscjames** [comment]
Now done apparently, thanks!

**Comment by jpmckinney** [comment]
@robredpath What is the plan for this repository? Archive it once all scrapers are migrated? (Assuming the tests with Scrapy go well and we don't change our minds about using a scraping framework.)

**Comment by jpmckinney** [comment]
From call: This repo is expected to become cross-repository issues and documentation (i.e. all code moved / removed).
