### ISSUE TITLE
Agree name of new data type in RHS

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#271]
One thing we said we would take this opportunity to do is add something to accommodate JSON Lines data. Currently the relationship of items are:

    Collection -> File -> Many Records/Releases

However with JSON Lines, one file may contain 1000’s of lines of data, and it would be good to track this. It allows for more modular error tracking (this already came up in Digiwhist where one line caused problems but the rest were fine and we couldn’t track it!). Now it will be:

    Collection -> File -> Item -> Many Records/Releases

It turns out, working on code around this today, this is actually applicable for more than JSON Lines. A lot of API's do not return valid OCDS data, but instead return a list of many pieces of valid OCDS Data! For instance, check out the "results" key in https://www.contractsfinder.service.gov.uk/Published/Notices/OCDS/Search?order=asc&page=1 The old system just stored them all as being under the same file (I guess none of them had the kind of error digiwhist has, or the problems tracking that error would have come up before!). But these cases can be tracked using the same system.

So: an File Item is a single piece of JSON that is attempting to be OCDS JSON: A release, record, release-package, record-package.

Sometimes, Files and File Items will be a one-to-one relationship, as each file will be one bit of data. But sometimes (like the UK example above, or a JSON Lines file) one file will have many items of data!

So to do in this ticket: agree the name "Item"?

Thanks,

**Comment by jpmckinney** [comment]
To clarify: My understanding is that LHS will be emitting either packages (if available) or releases/records (if the publisher has no packages). So, if LHS encounters JSON Lines, or a [JSON array of release packages](http://www.contratosabiertos.cdmx.gob.mx/api/contratos/array), or a JSON array of release packages at a `results` key (your link), then it should emit each item of the array, one at a time. That would mean that RHS just needs to know about packages and releases/records.

Or, is there a reason for LHS to accept data that might not look very much like OCDS without further source-specific processing?

**Comment by odscjames** [comment]
It would generally make the RHS more flexible and useful to be able to do this. Currently my prototype RHS already allows both to be sent; whole files, or data one item at a time from a file. (We already had the file concept it so it wasn't a big step). There is also the issue of tracking data API performance and errors - that will be discussed later, and for that it might be good to have this. Also, without the RHS being able to split up data Local Load will be limited. I'm guessing it's rare we'll be given a file with a "results" key to locally load, but probably more common we'll be given a JSON Lines file and asked to locally load it.

**Comment by jpmckinney** [comment]
I'm concerned that this means RHS now needs to be aware of a lot of source-specific issues, which I think is best treated in one place, i.e. the LHS.

The LHS should presumably have some functionality for tracking API errors/performance – it was one of the questions we asked when discussing Memorious and Scrapy (a feature they both offer).

To load a JSON Lines file directly on RHS, you would presumably just do something like `cat releases.json | ocdskingfisher local-load`, or for a file with an array of releases: `jq -crM .path.to.releases[] | ocdskingfisher local-load`.

I don't see what having support for anything more than packages/releases/records in RHS gives us, besides additional complexity.

**Comment by odscjames** [comment]
Will reply fully later but just to note https://github.com/open-contracting/kingfisher/issues/269#issuecomment-448506965 is relevant here - I think we need to consider whether we need this to make a easier to use system.

**Comment by jpmckinney** [comment]
@odscjames Please review this issue, and create any follow-up issues if relevant.

**Comment by jpmckinney** [comment]
@odscjames Pinging again.
