### ISSUE TITLE
Connect https://readthedocs.org/dashboard/ocdskingfisher-process to GitHub Web Hooks for ocdskingfisher-process repository

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#275]
So builds happen automatically. Thanks Rob!

**Comment by robredpath** [comment]
...how did ReadTheDocs become part of this? @odscjames

**Comment by odscjames** [comment]
I've mentioned doing docs the last few days. As we already use RTD for https://readthedocs.org/projects/ocdskingfisher/ and no problems have been raised with that, I assumed that would be fine as a continuation of existing practice - sorry if that was a bad assumption.

**Comment by robredpath** [comment]
Ah, ok, I see. RTD automatically sets up webhooks for projects, so I was confused as to why you wanted me to do it manually. Why do you want ocdskingfisher-process to build on pushes to this repo?

**Comment by odscjames** [comment]
Ah sorry, unclear title. Edited. (I never fully worked out RTD auto import thing and always ended up doing it by hand :-/ )

**Comment by robredpath** [comment]
@odscjames I've deleted and readded the project in RTD
