### ISSUE TITLE
Decide on whether we're using scrapyd or scrapy cloud

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#279]
Work here is:
- 1/2 day research into scrapy cloud 
- Write up findings + decision doc
- Facilitate a discussion to reach a decision

**Comment by robredpath** [comment]
Use free trial if possible, otherwise it's ok to expense a few credits

**Comment by jpmckinney** [comment]
We chose scrapyd due to memory and read-only filesystem constraints, and the complexity of available workarounds (storing in Google Cloud Storage, etc.).
