### ISSUE TITLE
Design documentation architecture for Kingfisher

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#280]

**Comment by robredpath** [comment]
+ then start to populate with existing docs

**Comment by odscjames** [comment]
Just to note we already have some docs in https://github.com/open-contracting/kingfisher-process/tree/master/docs and https://kingfisher-process.readthedocs.io/en/latest/

**Comment by jpmckinney** [comment]
Seems this is complete after #287 and #288.
