### ISSUE TITLE
Clean up Kingfisher repo

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#284]
Now new systems are in place ....

Maybe make new branch "master-old", and set up as a protected branch as "Master" is? This would be useful for history and any legacy work needed.

The "master" branch code and docs could be cleaned out to avoid confusing people new to the projects, with the docs in this repo providing an overview of how the two halves fit together and then linking out to the other repos/docs?

**Comment by jpmckinney** [comment]
Sounds good to me. I don't know if there are conventions, but I might prefer `archive` to `master-old`, since we use the term `archive` frequently in other contexts.

**Comment by odscjames** [comment]
I don't know of any conventions so "archive" it is.

@jpmckinney @robredpath Can you set up the same protections on "archive" as "master"? Thanks.

**Comment by odscjames** [comment]
Have changed salt so deploy uses archive branch.

**Comment by jpmckinney** [comment]
I've protected the branch the same as the other.

**Comment by odscjames** [comment]
All done
