### ISSUE TITLE
Fix Docs Menu

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#290]
The Index page doesn't have a toc with the other pages in - with the result that the menu jumps really oddly between https://ocdskingfisher.readthedocs.io/en/latest/#hosted-kingfisher and https://ocdskingfisher.readthedocs.io/en/latest/hosted.html and https://ocdskingfisher.readthedocs.io/en/latest/old.html

Add a TOC back at the bottom of the index page.

**Comment by jpmckinney** [comment]
Closed by #291. Please use "fixes #290" or "closes #290" in issue descriptions, to make this closure automatic.
