### ISSUE TITLE
DNS for Kingfisher servers

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#294]
Hi James,

Please can we get the following DNS set up? 

scrape.kingfisher.open-contracting.org -> 195.201.163.242
process.kingfisher.open-contracting.org -> 195.201.163.242
analyse.kingfisher.open-contracting.org -> 195.201.163.242
archive.kingfisher.open-contracting.org -> 195.201.195.185

**Comment by odscjames** [comment]
Now this is set up, we can add these hostnames as a new line into the Apache conf in

*  https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/apache/ocdskingfisherprocess.conf#L4
*  https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/apache/ocdskingfisherscrape.conf#L4

And change the docs here to reflect that?
