### ISSUE TITLE
Certain transforms should be marked as 'to happen' automatically.

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#296]
- Convert to 1.1
- Compile releases

**Comment by jpmckinney** [comment]
Re: defaults, let's make no-transforms the default, but allow configuration (e.g. environment variables or configuration file) such that the deployment used by analysts does these transforms automatically.

**Comment by odscjames** [comment]
Agree - this is similar to what we do with checks. https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisherprocess/config.py#L22

Question for analysts: The two transforms I assume want to happen one after the other - in which order should they happen?

@duncandewhurst

**Comment by duncandewhurst** [comment]
convert to 1.1 and then compile releases please, as we still need to run some queries against uncompiled releases, and so it's useful to have them all in 1.1 so that we only have to write one set of queries.
