### ISSUE TITLE
Write a script to copy files from scrape server to disk server

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#298]
- Check that each scrape is finished
- If so, rsync its files to the disk server and delete them
- Make it interactive for now

@odscjames @robredpath

**Comment by odscjames** [comment]
> Check that each scrape is finished

This is a simple SQL query - 

      select * from collection where store_end_at is not null and transform_type is null

However, that does introduce tight coupling with the database structure - but we are probably fine with that? As we already have that with the analyst queries?

One thought; just 'cos a row is in the database the files might not be on disk in the scrape server - it might be a local load or something. So do check files are actually on disk before trying to do something with them!

**Comment by robredpath** [comment]
PR is in! It doesn't explicitly check for a file but moves on safely if it encounters anything amiss

**Comment by jpmckinney** [comment]
https://github.com/open-contracting/kingfisher-archive
