### ISSUE TITLE
[1.1] Write a library to connect kingfisher to colab

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#299]

**Comment by robredpath** [comment]
This is done in a minimal way. There's some functions that still need to be added. The workaround until they are added is for people to copy/paste functions as they currently do.

**Comment by robredpath** [comment]
@pindec @mrshll1001 - it'd be good to get you up to speed on how to add functions to the library; @kindly tells me that @pindec has already been fixing bugs :) Do you have time over the next couple of weeks to add functions that you're currently copy/pasting? We can be available to discuss/review code over this sprint.

**Comment by pindec** [comment]
@robredpath great, thanks, will do. I think most of the functions are covered in the library, but I'm sure there are more handy things to add, and not all the functions are yet implemented.

**Comment by robredpath** [comment]
@kindly and @pindec can check in on this this week
