### ISSUE TITLE
Set up 'disk server':

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#301]
- OS
- SSH Keys
- Volumes/partitions/etc
- Salt

@robredpath

**Comment by robredpath** [comment]
The server has Ubuntu 18.04 LTS installed. `root` has all the usual keys for ODSC staff to access it. `archive` has all the usual keys, plus its own. The `archive` user can log into itself, on both kingfisher servers. This is either a brilliant or a terrible idea, but seems like a nice self-contained way for the servers to be able to talk securely. 

Out of the box, the server was partitioned with two large software RAID volumes - one 3.5TB, one 2TB. I *could* do some mdadm fettling to turn these into one large partition, but I feel like 3.5TB is enough for storing old files, while 2TB is enough for storing backups of other information from the main sever (eg dumps of the management tables). Especially if we compress them.  

All of the configuration is in salt, apart from the software RAID which is set by Hetzner.

**Comment by jpmckinney** [comment]
Moved to Done, so closing.
