### ISSUE TITLE
Ascertain frequency for automated runs of scrapers

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#305]

**Comment by robredpath** [comment]
@duncandewhurst @pindec @mrshll1001 @romifz @yolile 

How often do we want to run all the scrapers, automatically? Would once per quarter be sufficient? Or do we want different frequencies for different scrapers?

**Comment by mrshll1001** [comment]
I think once per quarter is reasonable as a default behaviour and then we can adjust based on any emergent needs. We can run scrapers manually ahead of a data review so I don't think we'd need much more granularity between reviews.

**Comment by pindec** [comment]
The key automated run use case is for MEL, so a quarterly run synced with MEL reporting dates would be ideal.

**Comment by robredpath** [comment]
Thanks both!

**Comment by robredpath** [comment]
@pindec how fresh does MEL data need to be? So, if we ran once every 3 months, starting 6 weeks before the expected MEL dates, is that ok?

**Comment by pindec** [comment]
@robredpath I think required freshness of MEL data is a @jpmckinney question :)

**Comment by jpmckinney** [comment]
That's fine, yes!
