### ISSUE TITLE
Automate scrapes 

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#308]
- Script to determine which scrapers to run and to trigger scrapes
- Cron job to run them (in Salt)

How we determine which to run:
- Exclude any that are currently running or have run within last month

**Comment by robredpath** [comment]
@odscjames is there a straightforward query for:

> Exclude any that are currently running or have run within last month

?

**Comment by odscjames** [comment]
select source_id from collection where transform_from_collection_id is null and store_end_at is not null and store_end_at >= '2019-01-01 10:00:00';

Will list the ones that have finished in the last month, so anything not in that list

**Comment by odscjames** [comment]
select source_id from collection where 
    transform_from_collection_id is null and ( store_end_at is not null or store_end_at >= '2019-01-01 10:00:00');

Should list ones currently running or ran in the last month, so anything not in that list.

**Comment by odscjames** [comment]
There's no such thing as a "List of all current sources" in the database so that will have to come from somewhere else

**Comment by robredpath** [comment]
Thanks, @odscjames . I'm planning on getting those off the filesystem - basically `ls kingfisher_scrapy/spiders | sed -e 'some sed magic' | grep -v recent_runs.txt`

**Comment by jpmckinney** [comment]
Closing for now, as need to improve kingfisher-process architecture for it to handle more regular scrapes as the number of publishers increases and datasets increase in size. Analysts can trigger scrapers manually for now.
