### ISSUE TITLE
Store comments with collections

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#311]
Problem: We have a lot of collections in our DB. It's hard to know what the state is sometimes - are they still in use? Who put them there - who can we even ask if they are in use?

Suggestion: Lets have an add-note option for an collection. The note contents would be stored in the postgres database. You would also be able to set a note when running a Scrapy spider, and that note would  be passed to the database.

Then we could establish a working convention that people loading data or starting scrapers should at least add a note with their name, so we know who to ask about a collection.

The note option could allow multiple notes. So if user A starts a scraper, but then user B starts analysing that data then user B can add a note saying "Please ask me before deleting this!"

I think this will help with #309

**Comment by mrshll1001** [comment]
I'm fine with this, Could be useful and the more internal transparency the better.

**Comment by yolile** [comment]
Totally agree!

**Comment by pindec** [comment]
Yes, this would be very useful.

**Comment by odscjames** [comment]
> Maybe we can also have a mark like "can be deleted" or something like that, that can be editable, so the person who load a test dataset or similar can mark the collection as "deleteable" (?) so then we can have a scheduled process that consults all the deleteables collections and delete them

This was put live last week and should do what your thinking? https://kingfisher-process.readthedocs.io/en/latest/cli-delete-collection.html :smile:

**Comment by pindec** [comment]
Delete collection looks good, thanks.

I note the docs say "A collection can only be deleted if it doesn’t have any transform". So work-flow wise, to delete a collection that has transforms, is it correct that we should:

- mark the transforms for deletion
- once they have been deleted, mark the source collection for deletion

Or can we flag them all, and the transforms will be deleted on the first pass, then the source on the second?

**Comment by odscjames** [comment]
> I note the docs say "A collection can only be deleted if it doesn’t have any transform". So work-flow wise, to delete a collection that has transforms, .....

Can I move this conversation to https://github.com/open-contracting/kingfisher-process/issues/105 ?

For this ticket, we are just waiting for https://github.com/open-contracting/kingfisher-scrape/pull/116 to be merged and we are done.

**Comment by odscjames** [comment]
Assigning this ticket to @kindly who will be checking that P.R. as part of his sprint work.

**Comment by odscjames** [comment]
Merged, and closing

**Comment by odscjames** [comment]
Reopening with a tiny doc update needed https://github.com/open-contracting/kingfisher-scrape/pull/124

**Comment by odscjames** [comment]
Done!
