### ISSUE TITLE
kf-views throws 'relation "read_only_user" does not exist' when running in vagrant

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#338]
When running views inside the Vagrant VM, it throws an error at the end as per the title.

**Comment by robredpath** [comment]
This also causes issues when testing

**Comment by odscjames** [comment]
Vagrant does not run the upgrade-database steps - that should fix this problem.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kingfisher Vagrant Issues raised during docs work](https://trello.com/c/v22E257r/206-kingfisher-vagrant-issues-raised-during-docs-work)

**Comment by odscjames** [comment]
Think now done
