### ISSUE TITLE
As an analyst making changes to kingfisher-views, I want to be able to connect to the postgres service within the Vagrant box from my host machine

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#339]
Identified during docs sprint

**Comment by odscjames** [comment]
Fair enough; should just need to open port and make sure the user details are logged somewhere.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kingfisher Vagrant Issues raised during docs work](https://trello.com/c/v22E257r/206-kingfisher-vagrant-issues-raised-during-docs-work)

**Comment by odscjames** [comment]
Think now done
