### ISSUE TITLE
Add data_partition variable to each source class and to base class

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#41]
To start with, these should be the 2 letter country code.

This will be used in the database to partition data into separate tables later. 

eg

````
class UKContractsFinderSource(Source):
    publisher_name = 'UK Contracts Finder'
    url = 'https://www.contractsfinder.service.gov.uk'
    source_id = 'uk_contracts_finder'
    data_partition = 'gb'
````

**Comment by jpmckinney** [comment]
Most countries have codes for subdivisions in https://en.wikipedia.org/wiki/ISO_3166-2 which we can consider using.

**Comment by jpmckinney** [comment]
I think this is on hold indefinitely, so closing.
