### ISSUE TITLE
Should we allow half sucessful fetches?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher#58]
Currently, if any part of the fetch fails the whole thing is marked as failed and no data is stored.

Do we want this? 

We have some sources that return a lot of data but also fail on a lot. Would it be better if we allowed the data we did fetch to be stored for analysis and review, while also making sure the part of it that failed is logged properly so that can be reported on to?

eg

  *  #7 Colombia The high page numbers pretty consistently give a 500, but the lower page numbers are fine.
  *  #16 Uguanda Awards and Contracts are broken, but Planning and tender are fine.

**Comment by timgdavies** [comment]
I would love to see ability to load partial and failed data, but just to know that this is what has happened. 

Would it be possible to maintain a log in the database of:

* Each file we've tried to fetch;
* Whether it was fetched successfully or not;
* Whether it has been loaded or not;

Having just triggered a load of the UK data, I'm waiting at the console thinking it would be lovely if I could query the DB to see how the fetching is going, and if any errors have been hit - and then to see how loading is going again by querying the db. 

I think as long as we have some clear queries that should be run to check the state of a 'version' for a given publisher, we should be permissive in loading.

**Comment by yolile** [comment]
I agree with allowing half sucessful fetches. Not only for the failed ones but also for the long ones that takes a lot of time to full fetch. For example, if I start fetching a source and then realize that the full fetch will take too many days to be done, I want to be able to stop the fetch at some point after had downloaded some amount of files, and then just run the store stage for make analysis with the sample that the tool already downloaded.

**Comment by odscjames** [comment]
A first quick go at this has been done! https://ocdskingfisher.readthedocs.io/en/master/cli-force-fetch-to-store.html 

That has limitations, so leaving this issue open to look at again later. (If we get parallisation right this will just happen as part of it, for instance.)

**Comment by jpmckinney** [comment]
I added comments to the commit, which are appearing at #222

**Comment by odscjames** [comment]
This will happen as part of the new 2 part system; closing
