### ISSUE TITLE
Establish procedure for sharing the server

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#89]
Right now, there's the Eagle of ETL, which is fine for development. But, in time, we will want to leave processes running for a long time, and probably only refresh the data periodically. We should establish a way that we can share the server effectively.

**Comment by robredpath** [comment]
https://docs.google.com/document/d/1Bhw0yH89ljsdl27jRMWruRWtjOH1sMYESTZ4mhL9bEQ/edit#

@timgdavies @duncandewhurst does the proposed workflow look workable for you?

@odscjames @kindly @tian2992 @Bjwebb does my assessment of the risks and mitigations look accurate? Can you foresee any problems with the proposed solution?

**Comment by duncandewhurst** [comment]
> Set up a cron to delete data older than 30 days from the database

Given that it can take a long while to run some of the scrapers, I'd rather we keep the last scraped version of the data for each publisher 'on file'.

That will be helpful for quick exploration, or when we want to answer queries along the lines of "are we seeing use of section/field X" without having to run scrapers to get fresh data for all the countries.

> does the proposed workflow look workable for you?

Workflow looks good, how do I access Redash?

**Comment by jpmckinney** [comment]
We seem to be sharing for a few months now without issue, so assuming issue is closed.
