### ISSUE TITLE
Set up bulk file storage

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#91]
One of the identified user needs is to be able to compare historical data to current data. A simple way to get this started is to:
- Set up a backup server with lots of disk space
- Add a function to the cli tool to create a gzipped tarball of the raw files and the sqlite metadata database
- Establish a procedure for copying the file to the backup server, and conversely restoring it to the database for analysis.

**Comment by odscjames** [comment]
This isn't needed for that user need - the program already lets you download the same source at different time points, have the raw files for both there at the same time, and have them in the raw tables at the same time in the DB.

**Comment by robredpath** [comment]
@odscjames as I understand it, there's only room on the current server for one copy of all of the data - I'm currently running a download of all the Ukraine data for @duncandewhurst and it's already at 46G for just the raw files.

**Comment by jpmckinney** [comment]
See also https://crm.open-contracting.org/issues/3634

**Comment by jpmckinney** [comment]
@robredpath How soon will we start using the disk server? It seems we've been paying for it for half a year without using it… If not within the next month, let's stop paying.

**Comment by robredpath** [comment]
This is now set up and the script will be in place by the end of the current sprint. We've certainly gone longer than I was anticipating without needing it!
